CREATE DATABASE [TesteUpd8]
GO

USE [TesteUpd8]
GO

CREATE TABLE [Cliente] (
    Id INT NOT NULL IDENTITY(1,1),
    Name VARCHAR(80) NOT NULL,
    BirthDate DATETIME NOT NULL,
    Sex VARCHAR(10) NOT NULL,
    Address NVARCHAR(200) NOT NULL,
    State VARCHAR(100) NOT NULL,
    City VARCHAR (50) NOT NULL,

    CONSTRAINT [PK_Cliente] PRIMARY KEY([Id])
)
GO